version: '3.3'
services:
  nextcloud_db:
    image: mariadb:10.5.8
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == worker]
      mode: "replicated"

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 16M

    volumes:
      - /data/nas/containers/uno/${WEBID}/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mzSbhudskzmcovcdsznjd9
      - MYSQL_PASSWORD=superMDPdbNEXTCL0UD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud_app:
    image: dockcms-registry.alieor.net/custom-app-nextcloud:23.0.3
    ports: 
      - 9000
    deploy:
      placement:
        constraints: [node.role == worker]
      mode: "replicated"

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.1'
          memory: 64M
    volumes:
      - /data/nas/containers/uno/${WEBID}/data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_PASSWORD=superMDPdbNEXTCL0UD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - traefik
    depends_on:
      - nextcloud_db

##################################################################################################################################################################
########## dockerfile de custom-nginx-nextcloud:1.0
#
#FROM nginx:1.18 
#RUN usermod nginx -u 33 -o
#
##################################################################################################################################################################
  nextcloud_web:
    image: dockcms-registry.alieor.net/custom-nginx-nextcloud:1.0
    deploy:
      placement:
        constraints: [node.role == worker]
      mode: "replicated"

      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_swarmpit-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.nextcloud-public-http.rule=Host(`$WEBURL`)
        - traefik.http.routers.nextcloud-public-http.entrypoints=http
        - traefik.http.routers.nextcloud-public-http.middlewares=https-redirect
        - traefik.http.routers.nextcloud-public-https.rule=Host(`$WEBURL`)
        - traefik.http.routers.nextcloud-public-https.entrypoints=https
        - traefik.http.routers.nextcloud-public-https.tls=true
        - traefik.http.services.nextcloud-public-https.loadbalancer.server.port=80
      

    volumes:
      - /data/nas/containers/uno/${WEBID}/data:/var/www/html
      - /data/nas/containers/uno/${WEBID}/cfg/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - nextcloud_app
    networks:
      - traefik

##################################################################################################################################################################
                                                              ## fin nextcloud
##################################################################################################################################################################
networks:
  traefik:
    external:
      name: traefik_swarmpit-public
